# Generated by Django 6.1 on 2026-08-21 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('links', '0004_link_click_limit_link_expires_at_link_is_archived_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('referrer', models.URLField(blank=True, max_length=2048, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('device', models.CharField(blank=True, default='Unknown', max_length=50)),
                ('browser', models.CharField(blank=True, default='Unknown', max_length=50)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_events', to='links.link')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['link', '-timestamp'], name='analytics_c_link_id_235add_idx'), models.Index(fields=['country'], name='analytics_c_country_68430a_idx'), models.Index(fields=['device'], name='analytics_c_device_912814_idx'), models.Index(fields=['browser'], name='analytics_c_browser_42ab2e_idx')],
            },
        ),
    ]
