# Generated by Django 6.1 on 2026-08-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_link_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='custom_alias',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
