# Generated by Django 6.1 on 2026-08-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_link_custom_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='click_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='link',
            name='is_password_protected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='link',
            name='password_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
