# Generated by Django 6.1 on 2026-08-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_link_click_limit_link_expires_at_link_is_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='folder',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
