# Generated by Django 6.1 on 2026-08-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_link_folder_link_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='redirect_type',
            field=models.PositiveSmallIntegerField(choices=[(302, '302 Temporary'), (301, '301 Permanent')], default=302, help_text='HTTP redirect status used when the short link redirects to its destination.'),
        ),
    ]
